package com.mitsuki.ehit.const

object DataKey {
    const val GALLERY_INFO = "GALLERY_INFO"
    const val GALLERY_INDEX = "GALLERY_INDEX"
    const val GALLERY_ID = "GALLERY_ID"
    const val GALLERY_NAME = "GALLERY_NAME"
    const val GALLERY_TOKEN = "GALLERY_TOKEN"
    const val IMAGE_TOKEN = "IMAGE_TOKEN"
    const val GALLERY_PAGE = "GALLERY_PAGE"
    const val GALLERY_DETAIL = "GALLERY_DETAIL"
    const val IMAGE_CACHE_KEY = "IMAGE_CACHE_KEY"

    const val GALLERY_LIST_TYPE = "GALLERY_LIST_TYPE"
    const val GALLERY_LIST_INIT_KEY = "GALLERY_LIST_INIT_KEY"


    const val GALLERY_PAGE_SOURCE = "GALLERY_PAGE_SOURCE"

    const val GALLERY_QUICK_TYPE = "GALLERY_QUICK_TYPE"
    const val GALLERY_QUICK_KEY = "GALLERY_QUICK_KEY"

    const val GALLERY_FRAGMENT_CODE = "GALLERY_FRAGMENT_CODE"
    const val GALLERY_SEARCH_KEY = "GALLERY_SEARCH_KEY"
}